schema:
  fields:
    - name: "First_Day_of_Leave"
      type: "STRING"
      mode: "NULLABLE"
    - name: "Leave_Type_excluding_Family"
      type: "STRING"
      mode: "NULLABLE"
    - name: "Last_Day_of_Leave_Estimated"
      type: "STRING"
      mode: "NULLABLE"
    - name: "Last_Day_of_Leave_Actual"
      type: "STRING"
      mode: "NULLABLE"
    - name: "Leave_Reason"
      type: "STRING"
      mode: "NULLABLE"
    - name: "Worker_WID"
      type: "STRING"
      mode: "NULLABLE"
    - name: "Leave_of_Absence_Request_WID"
      type: "STRING"
      mode: "NULLABLE"
    - name: "Transaction_Status"
      type: "STRING"
      mode: "NULLABLE"
